// @ts-nocheck

import type {Metadata} from "next";
import {EB_Garamond} from '@next/font/google';
import {ChkraProvider} from './providers'
import "./globals.css";

const ebGaramond = EB_Garamond({
    subsets: ["latin"],
    display: "swap",
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={ebGaramond.className}>
        <body>
        <ChkraProvider>
            {children}
        </ChkraProvider>
        </body>
        </html>
    );
}
